# Generated by Django 5.2.7 on 2025-11-07 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCategories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'career_category',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_pay', models.AutoField(primary_key=True, serialize=False)),
                ('is_trial', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(blank=True, max_length=45, null=True)),
                ('payment_status', models.CharField(max_length=45)),
                ('payment_method', models.CharField(blank=True, max_length=45, null=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('receipt_img', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id_career', models.AutoField(primary_key=True, serialize=False)),
                ('name_career', models.CharField(max_length=80)),
                ('desc_career', models.TextField(max_length=250)),
                ('duration_years', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.careercategories')),
            ],
            options={
                'db_table': 'career',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id_mentor', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sessions', models.IntegerField(default=0)),
                ('is_mentor', models.BooleanField(default=False)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='mentors/')),
                ('description', models.TextField(max_length=350)),
                ('alt_career', models.TextField(blank=True, max_length=60, null=True)),
                ('language', models.TextField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.career')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'mentor',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id_professional', models.AutoField(primary_key=True, serialize=False)),
                ('pro_title', models.CharField(max_length=60)),
                ('experience_years', models.IntegerField(default=0)),
                ('college', models.CharField(blank=True, max_length=55, null=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('cv_url', models.TextField(blank=True, max_length=100, null=True)),
                ('graduation_year', models.DateField()),
                ('work_experience', models.JSONField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.mentor')),
            ],
            options={
                'db_table': 'professional_profile',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=80, unique=True)),
                ('schedule_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('session_status', models.CharField(max_length=50)),
                ('meeting_url', models.TextField(blank=True, max_length=500, null=True)),
                ('meeting_platform', models.CharField(max_length=45)),
                ('session_notes', models.TextField(max_length=250)),
                ('student_feedback', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recording_url', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mentor')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=60)),
                ('current_semester', models.IntegerField()),
                ('work_experience', models.JSONField(blank=True, null=True)),
                ('skills', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.mentor')),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id_learner', models.AutoField(primary_key=True, serialize=False)),
                ('educational_level', models.CharField(blank=True, max_length=45, null=True)),
                ('current_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('interests', models.TextField(blank=True, max_length=100, null=True)),
                ('career_interests', models.TextField(blank=True, max_length=100, null=True)),
                ('prefered_schedule', models.CharField(blank=True, max_length=20, null=True)),
                ('is_learner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'learner',
            },
        ),
        migrations.CreateModel(
            name='DataSession',
            fields=[
                ('id_data', models.AutoField(primary_key=True, serialize=False)),
                ('is_present', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'data_session',
            },
        ),
    ]
